name: "Oplossing"
on:
  push:
    branches-ignore:
      - l10n_develop
      - gh-pages
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - 'monitoring/grafana-dashboard.json'
      - 'screenshots/**'
    tags-ignore:
      - '*'
  pull_request:
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - 'data/static/i18n/*.json'
      - 'frontend/src/assets/i18n/*.json'
env:
  NODE_DEFAULT_VERSION: 20
  ANGULAR_CLI_VERSION: 17
  CYCLONEDX_NPM_VERSION: '^1.12.0'
jobs:
  SCA:
    runs-on: ubuntu-latest
    steps:
      - name: " checkout git repository"
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      - name: "Use Node.js 18"
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - name: Create SBOM step
  # see for usage: https://www.npmjs.com/package/%40cyclonedx/cyclonedx-npm
        run: npx @cyclonedx/cyclonedx-npm --output-format JSON --output-file sbom.json --verbose package.json
      - name: curl
        run: "curl -X POST -H 'X-Api-Key: HRKU-90822da0-9ae8-4371-b444-35d163482e91' -F 'project=48ee37bb-1dd0-477c-8291-6b252759b513' -F 'bom=@sbom.json' https://dependency.portasecura.com/api/v1/bom"
  SAST:
    needs: [SCA]
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript-typescript' ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac #v4.0.0
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
        queries: security-extended
        config: |
          paths-ignore:
            - 'data/static/codefixes'
    - name: Autobuild
      uses: github/codeql-action/autobuild@v2
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

  DAST:
    needs: [SAST]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac #v4.0.0   
      - name: Install Heroku CLI # <- IMPORTANT!!! Make sure the cli is installed before using the action
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh 
      - uses: akhileshns/heroku-deploy@v3.14.15 # This is the action
        with:
          heroku_api_key: HRKU-90822da0-9ae8-4371-b444-35d905682e92
          heroku_app_name: "testglenn" #Must be unique in Heroku
          heroku_email: "mboeynaems@outlook.com"
      - name: DAST OWASP ZAP scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
    # Target URL
          target: https://testglenn-8a31421a27d4.herokuapp.com/#/
  
    
